openapi: 3.0.0
info:
  title: AL Coding Standards API
  version: 1.0.0
  description: API to access AL coding standards markdown document
servers:
  - url: https://api.github.com/repos/LewisHyett/MCPTest/contents
paths:
  /coding-standards.md:
    get:
      summary: Get AL coding standards
      description: Retrieves the content of the AL coding standards markdown file
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: Base64 encoded markdown content
                  encoding:
                    type: string
                    example: "base64"

